#include "net/identity.h"

#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include <openssl/x509.h>

#include <cstdio>
#include <cstring>
#include <sys/stat.h>
#include <unistd.h>

namespace rivt::net {

static std::string home_subdir(const char *env, const char *fallback, const char *sub) {
    const char *base = getenv(env);
    std::string dir;
    if (base && *base) {
        dir = std::string(base) + "/rivt";
    } else {
        const char *home = getenv("HOME");
        dir = std::string(home ? home : ".") + "/" + fallback + "/rivt";
        // Build intermediate dirs with default perms; the leaf gets 0700.
        std::string acc;
        for (size_t i = 0; i < dir.size(); i++) {
            if (dir[i] == '/' && i > 0) mkdir(acc.c_str(), 0755);
            acc += dir[i];
        }
    }
    mkdir(dir.c_str(), 0700);
    if (sub) {
        dir += "/";
        dir += sub;
    }
    return dir;
}

static std::string read_file(const std::string &path) {
    FILE *f = fopen(path.c_str(), "r");
    if (!f) return {};
    std::string out;
    char buf[4096];
    size_t n;
    while ((n = fread(buf, 1, sizeof buf, f)) > 0) out.append(buf, n);
    fclose(f);
    return out;
}

std::unique_ptr<Identity> Identity::load_or_create(const std::string &state_dir) {
    std::string dir = state_dir;
    if (dir.empty() && getenv("RIVT_STATE_DIR")) dir = getenv("RIVT_STATE_DIR");
    if (dir.empty()) dir = home_subdir("XDG_STATE_HOME", ".local/state", nullptr);
    mkdir(dir.c_str(), 0700);

    auto id = std::make_unique<Identity>();
    id->m_key_path = dir + "/device_key.pem";
    id->m_cert_path = dir + "/device_cert.pem";

    EVP_PKEY *key = nullptr;
    if (FILE *f = fopen(id->m_key_path.c_str(), "r")) {
        key = PEM_read_PrivateKey(f, nullptr, nullptr, nullptr);
        fclose(f);
    }
    if (!key) {
        key = EVP_EC_gen("P-256");
        if (!key) return nullptr;
        FILE *f = fopen(id->m_key_path.c_str(), "w");
        if (!f) { EVP_PKEY_free(key); return nullptr; }
        chmod(id->m_key_path.c_str(), 0600);
        PEM_write_PrivateKey(f, key, nullptr, nullptr, 0, nullptr, nullptr);
        fclose(f);
    }

    X509 *cert = nullptr;
    if (FILE *f = fopen(id->m_cert_path.c_str(), "r")) {
        cert = PEM_read_X509(f, nullptr, nullptr, nullptr);
        fclose(f);
    }
    if (cert) {
        // The cert must match the key (e.g. key regenerated by hand).
        if (X509_check_private_key(cert, key) != 1) {
            X509_free(cert);
            cert = nullptr;
        }
    }
    if (!cert) {
        cert = X509_new();
        X509_set_version(cert, 2);
        uint8_t serial[8];
        RAND_bytes(serial, sizeof serial);
        serial[0] &= 0x7f;
        ASN1_INTEGER *sn = ASN1_INTEGER_new();
        BIGNUM *bn = BN_bin2bn(serial, sizeof serial, nullptr);
        BN_to_ASN1_INTEGER(bn, sn);
        X509_set_serialNumber(cert, sn);
        ASN1_INTEGER_free(sn);
        BN_free(bn);

        X509_gmtime_adj(X509_get_notBefore(cert), -60 * 60 * 24);
        X509_gmtime_adj(X509_get_notAfter(cert), 60L * 60 * 24 * 365 * 20);

        char host[256] = "rivt";
        gethostname(host, sizeof host - 1);
        std::string cn = std::string("rivt-") + host;
        X509_NAME *name = X509_get_subject_name(cert);
        X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC,
                                   (const unsigned char *)cn.c_str(), -1, -1, 0);
        X509_set_issuer_name(cert, name);
        X509_set_pubkey(cert, key);
        if (X509_sign(cert, key, EVP_sha256()) <= 0) {
            X509_free(cert);
            EVP_PKEY_free(key);
            return nullptr;
        }
        FILE *f = fopen(id->m_cert_path.c_str(), "w");
        if (!f) { X509_free(cert); EVP_PKEY_free(key); return nullptr; }
        PEM_write_X509(f, cert);
        fclose(f);
    }

    uint8_t *der = nullptr;
    int dlen = i2d_X509(cert, &der);
    if (dlen > 0) {
        uint8_t hash[SHA256_DIGEST_LENGTH];
        SHA256(der, dlen, hash);
        char hex[2 * SHA256_DIGEST_LENGTH + 1];
        for (int i = 0; i < SHA256_DIGEST_LENGTH; i++)
            snprintf(hex + 2 * i, 3, "%02x", hash[i]);
        id->m_fingerprint = hex;
        OPENSSL_free(der);
    }
    id->m_cert_pem = read_file(id->m_cert_path);

    X509_free(cert);
    EVP_PKEY_free(key);
    return id;
}

std::string Identity::authorized_bundle_path(const std::string &config_dir) {
    if (config_dir.empty() && getenv("RIVT_AUTHORIZED_CERTS"))
        return getenv("RIVT_AUTHORIZED_CERTS");
    std::string dir = config_dir.empty()
                          ? home_subdir("XDG_CONFIG_HOME", ".config", nullptr)
                          : config_dir;
    mkdir(dir.c_str(), 0700);
    std::string path = dir + "/authorized_certs.pem";
    if (access(path.c_str(), F_OK) != 0) {
        FILE *f = fopen(path.c_str(), "w");
        if (f) {
            chmod(path.c_str(), 0600);
            fclose(f);
        }
    }
    return path;
}

static std::string b64(const uint8_t *data, size_t len) {
    static const char tbl[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string out;
    for (size_t i = 0; i < len; i += 3) {
        uint32_t v = data[i] << 16 | (i + 1 < len ? data[i + 1] << 8 : 0) |
                     (i + 2 < len ? data[i + 2] : 0);
        out += tbl[(v >> 18) & 63];
        out += tbl[(v >> 12) & 63];
        out += i + 1 < len ? tbl[(v >> 6) & 63] : '=';
        out += i + 2 < len ? tbl[v & 63] : '=';
    }
    return out;
}

static EVP_PKEY *load_key(const std::string &path) {
    FILE *f = fopen(path.c_str(), "r");
    if (!f) return nullptr;
    EVP_PKEY *key = PEM_read_PrivateKey(f, nullptr, nullptr, nullptr);
    fclose(f);
    return key;
}

std::string Identity::spki_b64() const {
    EVP_PKEY *key = load_key(m_key_path);
    if (!key) return {};
    uint8_t *der = nullptr;
    int len = i2d_PUBKEY(key, &der);
    EVP_PKEY_free(key);
    if (len <= 0) return {};
    std::string out = b64(der, len);
    OPENSSL_free(der);
    return out;
}

std::string Identity::spki_der() const {
    EVP_PKEY *key = load_key(m_key_path);
    if (!key) return {};
    uint8_t *der = nullptr;
    int len = i2d_PUBKEY(key, &der);
    EVP_PKEY_free(key);
    if (len <= 0) return {};
    std::string out((const char *)der, len);
    OPENSSL_free(der);
    return out;
}

std::string Identity::sign_b64(const std::string &payload) const {
    EVP_PKEY *key = load_key(m_key_path);
    if (!key) return {};
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    uint8_t der[128];
    size_t der_len = sizeof der;
    bool ok = EVP_DigestSignInit(ctx, nullptr, EVP_sha256(), nullptr, key) == 1 &&
              EVP_DigestSign(ctx, der, &der_len, (const uint8_t *)payload.data(),
                             payload.size()) == 1;
    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(key);
    if (!ok) return {};

    // DER SEQUENCE{ INTEGER r, INTEGER s } -> raw r||s (32+32), the
    // encoding WebCrypto verifies.
    uint8_t raw[64] = {0};
    size_t i = (der[1] & 0x80) ? 3 : 2;
    for (int part = 0; part < 2; part++) {
        if (i + 2 > der_len || der[i] != 0x02) return {};
        size_t len = der[i + 1];
        i += 2;
        const uint8_t *v = der + i;
        i += len;
        while (len > 32) { v++; len--; }  // strip leading zero pad
        memcpy(raw + part * 32 + (32 - len), v, len);
    }
    return b64(raw, 64);
}

} // namespace rivt::net
